### PR TITLE
:construction_worker: Updated the Ubuntu CI to include 24.04 and newer compiler versions

### PR DESCRIPTION
**Pull request by marcelwa**
## Description

Dropped `ubuntu-20.04` and added `ubuntu-24.04`. Additionally, updated the C++ compilers to newer versions

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [ ] I have added a changelog entry.
- [x] I have created/adjusted the Python bindings for any new or updated functionality.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [x] The pull request introduces no new warnings and follows the project's style guidelines.

### CODE REVIEW

**Comment by marcelwa** [comment]
@Drewniok the build with GCC 14 fails here because of the `convert_to_siqad_coordinates` function. It is a GCC bug. Do you think, you could rewrite the function anyway to reduce nesting and return type inference to assist the compiler?

**Comment by marcelwa** [comment]
> @Drewniok the build with GCC 14 fails here because of the `convert_to_siqad_coordinates` function. It is a GCC bug. Do you think, you could rewrite the function anyway to reduce nesting and return type inference to assist the compiler?

The issue occurs on macOS as well. See, e.g., here: https://github.com/cda-tum/fiction/actions/runs/10387750687/job/28761888544?pr=499

Hope that helps with reproducibility.

**Comment by Drewniok** [comment]
> @Drewniok the build with GCC 14 fails here because of the `convert_to_siqad_coordinates` function. It is a GCC bug. Do you think, you could rewrite the function anyway to reduce nesting and return type inference to assist the compiler?
are al
@marcelwa Oh, that's not good. Sure, I'll have a look asap. I'll try my best, but this convert function has already caused me a lot of worries.

**Comment by marcelwa** [comment]
> > @Drewniok the build with GCC 14 fails here because of the `convert_to_siqad_coordinates` function. It is a GCC bug. Do you think, you could rewrite the function anyway to reduce nesting and return type inference to assist the compiler?
> > are al
> > @marcelwa Oh, that's not good. Sure, I'll have a look asap. I'll try my best, but this convert function has already caused me a lot of worries.

Understandable. It is not a simple function. I spent some time myself (maybe 30 min) and could not fix the issue. It probably requires dissecting the code a bit more.

**Comment by Drewniok** [comment]
@marcelwa Finally I could fix it! I am not sure where to put the code change. We can close #501 and change the title of #499 to make it clear that the code was also slightly changed. What do you think?

**Comment by marcelwa** [comment]
> @marcelwa Finally I could fix it! I am not sure where to put the code change. We can close #501 and change the title of #499 to make it clear that the code was also slightly changed. What do you think?

Agreed. That would be good. Thank you so much for investigating the problem.

**Pull request merged**
