### PR TITLE
✅ Update Unit Tests and Exclude Long-Running Tests in Debug Mode Using ``NDEBUG``

### PR DESCRIPTION
**Pull request by Drewniok**
## Description

This PR updates unit tests and uses ``NDEBUG`` to exclude long-running tests in debug mode.

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [ ] I have added a changelog entry.
- [ ] I have created/adjusted the Python bindings for any new or updated functionality.
- [x] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

### CODE REVIEW

**Comment by marcelwa** [comment]
This should be possible without CMake changes. The vast majority of compilers set a flag called `NDEBUG` when in Release mode (not debug). So you can check for
```c++
#ifndef NDEBUG
    // Debug mode
#else
    // Release mode
#endif
```
While not technically guaranteed by ISO C++, the standard itself depends on it, too, as it uses it for conditionally disabling `assert` statements: https://en.cppreference.com/w/c/error/assert

It is thus fairly safe to use as all compilers we continuously test for should implement `NDEBUG`.

**Comment by Drewniok** [comment]
> This should be possible without CMake changes. The vast majority of compilers set a flag called `NDEBUG` when in Release mode (not debug). So you can check for
> 
> ```c++
> #ifndef NDEBUG
>     // Debug mode
> #else
>     // Release mode
> #endif
> ```
> 
> While not technically guaranteed by ISO C++, the standard itself depends on it, too, as it uses it for conditionally disabling `assert` statements: https://en.cppreference.com/w/c/error/assert
> 
> It is thus fairly safe to use as all compilers we continuously test for should implement `NDEBUG`.

Wow! Thank you!

**Comment by Drewniok** [comment]
> Your changes are fine and we can gladly merge them like this. However, if you are feeling fancy, you could define new macros `RELEASE_ONLY_TEST_CASE`, `RELEASE_ONLY_TEMPLATE_TEST_CASE`, and `RELEASE_ONLY_SECTION` in a separate file that wrap the `NDEBUG` checks for us.

That's a great idea. Let's merge this and we can add it later.

**Review by marcelwa — APPROVED** [review]

**Comment by marcelwa** [comment]
Don't forget to update the PR description given the latest changes ;)

**Pull request merged**
